### ISSUE TITLE
Not a template repository

### ISSUE THREAD

**Issue by jorgranados** [matthiasott/eleventy-plus-vite#11]
HI @matthiasott , I'm trying to test your 11ty starter but he step "Start by [generating a new repository based on this project](https://github.com/matthiasott/eleventy-plus-vite/generate)" fails because apparently the repository is not a template. 
`Could not clone: matthiasott/eleventy-plus-vite is not a template repository.`

**Comment by matthiasott** [comment]
@jorgranados Thanks a lot for letting me know – and sorry for the late response! This is fixed now, I missed to check the box in the settings.
