### ISSUE TITLE
Vite 5?

### ISSUE THREAD

**Issue by groenroos** [matthiasott/eleventy-plus-vite#15]
Does this template actually utilise the Vite 5.1.5 called for in `package.json`?

`eleventy-plugin-vite` still specifies Vite 4.x (at least until 11ty/eleventy-plugin-vite#40 is released on npm); and for me at least, running `npm run build` on this repo outputs:

```
vite v4.5.2 building for production...
```

**Comment by matthiasott** [comment]
Thanks @groenroos! I will check this… 🤔

**Comment by KiwiKilian** [comment]
If you check your project folder there will be Vite v4 installed into `node_modules/@11ty/eleventy-plugin-vite/node_modules/vite`, because it's a dependency of `eleventy-plugin-vite` specified to v4. If just created a PR to upgrade https://github.com/11ty/eleventy-plugin-vite/pull/46.
