### ISSUE TITLE
Using "ctrl + c" on mac does not stop process on version 1.2.0

### ISSUE THREAD

**Issue by davehulse** [matthiasott/eleventy-plus-vite#17]
When running the "start" or "serve" npm scripts on version 1.2.0, using "ctrl + c" does not shut down the process running on port 8080. Compared to previous version this was not a problem.

**Comment by hrxkr** [comment]
I faced the same issue with stock installation of Vite and Eleventy 3 beta. I used `Ctrl + \` to kill the process as `Ctrl + c` didnt work. So this issue might not be in Eleventy Plus Vite starter.

**Comment by davehulse** [comment]
Thanks for the info @hrxkr 👍

**Comment by KiwiKilian** [comment]
Hey @davehulse and @hrxkr, could you please share more about your environment (operating system and node version) over at https://github.com/11ty/eleventy-plugin-vite/issues/49? Thanks!

**Comment by hrxkr** [comment]
Hey @KiwiKilian 
Sure! 

macOS: Ventura 13.6.9
Node: 20.17.0
Npm: 10.8.2
