### ISSUE TITLE
fonts are not used on any page.

### ISSUE THREAD

**Issue by aloxe** [matthiasott/eleventy-plus-vite#18]
I am wondering why are the fonts so precisely separated in subset/extended woff files, preloaded with critical FOFT strategy and are not used anywhere in the styles. The only font-family call in the css is:
```
body {
    font-family: sans-serif;
}
```
As a result, the font is loaded because of FOTF but not applied on the page.

**Comment by KiwiKilian** [comment]
The fonts are used as soon as the classes are applied, just below the line you are referencing: https://github.com/matthiasott/eleventy-plus-vite/blob/main/src/assets/css/2-design-tokens/_fonts.scss#L52-L57

**Comment by aloxe** [comment]
Oh I see, the critical FOFT in base.njk adds `fonts-loaded-1` and `fonts-loaded-2` classes to the html tag.
