### ISSUE TITLE
Passthrough file copy / Vite build not working for `--serve`

### ISSUE THREAD

**Issue by matthiasott** [matthiasott/eleventy-plus-vite#4]
The new passthrough file copy and the Vite build step does not yet work when using `--serve`.

This is related to `eleventy-plugin-vite`: https://github.com/11ty/eleventy-plugin-vite/blob/3a2ae8c51c6fb6a64c04bf7452b075552a1b2368/.eleventy.js#L44

**Comment by simplerethink** [comment]
Looks like your open issues with [eleventy-plugin-vite](https://github.com/11ty/eleventy-plugin-vite) are part of this as well?
